Jenkinsfile.cib: commit into docs-cibseven-de repo

diff --git a/Jenkinsfile.cib b/Jenkinsfile.cib
--- a/Jenkinsfile.cib
+++ b/Jenkinsfile.cib
@@ -301,23 +301,24 @@ pipeline {
                     checkout changelog: false, poll: false, scm: scmGit(branches: [[name: 'main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'engine-rest/docs/target/repo']], userRemoteConfigs: [[credentialsId: 'credential-github-cib-seven-access-token', url: 'https://github.com/cibseven/docs-cibseven-de.git']])
                     sh 'mkdir -p engine-rest/docs/target/repo/rest/cibseven/1.0'
                     sh 'mv -f engine-rest/docs/target/index.html engine-rest/docs/target/repo/rest/cibseven/1.0/index.html'
-                    sh """#!/bin/bash
-                        cd engine-rest/docs/target/repo
-                        git status
-                        git add *
-                        if ! git diff-index --quiet HEAD --
-                        then
-                            echo "index.html was changed -> commit changes"
-                            git commit -am "Update open API index.html"
+                    dir('engine-rest/docs/target/repo') {
+                        sh """#!/bin/bash
+                            pwd
+                            git status
+                            git add *
+                            if ! git diff-index --quiet HEAD --
+                            then
+                                echo "index.html was changed -> commit changes"
+                                git commit -am "Update open API index.html"
 
-                            echo "Push to github"
-                            # always return true so that the build does not fail if there are no changes
-                            git push origin || true
-                        else
-                            echo "index.html was not changed -> nothing to do more"
-                        fi
-                        cd ../../../..
-                    """
+                                echo "Push to github"
+                                # always return true so that the build does not fail if there are no changes
+                                git push origin || true
+                            else
+                                echo "index.html was not changed -> nothing to do more"
+                            fi
+                        """
+                    }
 
                     // clean up
                     withMaven {
